### ISSUE TITLE
Cannot delete files from the file menu in atheos

### ISSUE THREAD

**Issue by wh33t** [Atheos/Atheos#180] opened 2021-04-26 03:04 UTC
I right click, delete. The file doesn't delete. 

www-data owns the entire html/ apache2 directory. Permissions set to 0777. Still doesn't delete. 

Atheos sits in the server at html/atheos

The projects it edits sit along side it like html/project1 or html/project2

Atheos works fine otherwise. 

Anyone else having this issue?

I'm using v4.2.0

**Comment by HLSiira** [comment] 2021-04-26 04:10
Does the console give any errors?

And were the project folders created by Atheos? As in, you didn't use the Terminal to make the projects and then add them to Atheos later

**Comment by wh33t** [comment] 2021-04-26 04:37
If by console, you mean the little floating widget thing that appears when you "save" and such, no. Nothing comes up.

The files and directory were all created via terminal, and then added into Atheos as a project.

**Comment by HLSiira** [comment] 2021-04-26 10:12
If you create a folder using the terminal, you are the owner by default, not www-data.

When you run `ls - a` inside of `/var/www/html` scary do you get?

**Comment by wh33t** [comment] 2021-04-26 15:42
> If you create a folder using the terminal, you are the owner by default, not www-data.
> 
> When you run `ls - a` inside of `/html` scary do you get?

I have chown'd -R the entire webroot to www-data:www-data. www-data owns everything. Like I first mentioned, www-data owns the entire thing, and even with it the entire webroot set to 0777 the files still do not delete. 

`drwxrwxr-x 13 www-data www-data 4096 Mar  5 14:00 atheos
-rwxrwxr-x  1 www-data www-data    0 Mar  5 13:40 index.html
drwxrwxr-x  3 www-data www-data 4096 Mar  5 14:14 project1
drwxrwxr-x  5 www-data www-data 4096 Apr 25 20:22 project2
drwxrwxr-x  7 www-data www-data 4096 Apr  7 19:50 project3`

**Comment by HLSiira** [comment] 2021-04-26 19:35
Ooh Roger. Sorry, I forgot to update my reply but I wanted to add on:

I'm not trying to say something isn't wrong with Atheos, I'll be digging into the code when I can today or tomorrow, but you mentioned permissions and I've had issues where I forgot to `chown` stuff.

When you say files, do you specifically mean files or folders as well? I just pushed a fix to the dev branch where you couldn't delete folders but I thought that bug was only on dev

**Comment by wh33t** [comment] 2021-04-26 23:53
Hey, no worries at all! I deeply appreciate all you've done for the project. It's a great tool. 

I cannot delete files or directories using the right click context menu from the left pane file browser. Oddly I can create and edit them just fine though. 

Should I try updating to 4.3.0?

**Comment by HLSiira** [comment] 2021-04-26 23:56
You could, I honestly am not sure what the issue could be. You've really found a strange bug, I am definitely going to have to downgrade and try to fix it if I can find it. 

It's probably a really small typo somewhere in the file manager class, almost all my bugs are typos.

**Comment by wh33t** [comment] 2021-04-27 00:01
Do you think it's related to Ubuntu-server? I'm on w/e the latest version is and I installed the LAMP stack through tasksel. I thought this particular setup for a home dev environment would be pretty common because it's honestly only like 10 terminal commands and you have it all up and running.

**Comment by HLSiira** [comment] 2021-04-27 00:41
I doubt it. It might be, but I run on a common Ubuntu lamp stack. Never had a single issue that wasn't caused by the idiot who makes this thing (me lol)

**Comment by wh33t** [comment] 2021-04-27 00:52
A little self deprecation goes a long way dude lol.

**Comment by HLSiira** [comment] 2021-04-27 01:09
I honestly can't think of a way to replicate the bug without being on your system myself

Do you get any php errors in your error.log?

**Comment by wh33t** [comment] 2021-04-27 01:21
LOL, duh. I should have checked the error log myself. Here ya go. 

> Mon Apr 26 08:43:18.446715 2021] [php7:error] [pid 596] [client 192.168.1.122:37156] PHP Fatal error:  Uncaught ErrorException: Non-static method Common::rDelete() should not be called statically in /var/www/html/atheos/components/filemanager/class.filemanager.php:54\nStack trace:\n#0 /var/www/html/atheos/components/filemanager/class.filemanager.php(54): {closure}()\n#1 /var/www/html/atheos/components/filemanager/controller.php(49): Filemanager->delete()\n#2 /var/www/html/atheos/controller.php(44): require('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/atheos/components/filemanager/class.filemanager.php on line 54

**Comment by HLSiira** [comment] 2021-04-27 01:38
Ahh that's an easy fix then, you need to find rDelete and add the word static in it, much like it is in this:
https://github.com/Atheos/Atheos/blob/95dd700d212b06d2cbd930f6f5f51cfc7b088263/traits/helpers.php#L134

**Comment by wh33t** [comment] 2021-04-27 01:51
Is there any reason this is a problem for me, but not others?

Thanks so much for the support btw.

**Comment by HLSiira** [comment] 2021-04-27 02:23
Actually no. You said you're on v4.2.0 originally, which is an older version and it didn't have the same code structure, in fact, it's almost completely different from how v4.3.0 is set up, traits don't exist in that version, however moving to a new version ALSO had the same issue, I just looked at the source for both.
v4.3.0 would cause the issue you posted in the error logs, v4.2.0 wouldn't, but you had the identical bug both times.

My best guess is that: It worked for me, since I fix bugs non-stop and sometimes lose track of which bug gets fixed when, and most everyone else probably either used the master branch, not the releases, which always have the latest features, OR they used the releases, hit the bug, and decided it was crap software and didn't open an issue.

Honestly your guess is as good as mine, if not better since you actually had the code.

**Closed** 2021-04-27 23:59 UTC
